version: '2'
services:
    trisilk-app:
        image: trisilk
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://trisilk-mysql:3306/trisilk?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    trisilk-mysql:
        extends:
            file: mysql.yml
            service: trisilk-mysql
